name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install || true

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .          # <-- root থেকে build হবে
          destination: ./_site
